FORMAT: 1A
HOST: http://quiz.quarasique.ru/

# Quiz API

API для онлайн-викторины - упрощенной интеллектуальной игры "Квиз". 

Лимит запросов (если не указано иное): не более 60 в течение 60 секунд.

# Group Пользователи

Методы для работы с пользователями

## /users

### Создание пользователя [POST]

Пользователь должен иметь следующие аттрибуты:
+ username: строка длиной от 4 до 20 символов. username должны быть уникальными.
+ password: строка длиной до 72 символов включительно
+ password_confirmation: строка, соответствующая аттрибуту password

Аттрибут password_confirmation опционален и может не включаться в тело запроса

Лимит запросов: не более 5 в течение 20 секунд

+ Request (application/json)
        
        {
            "username": "JonhDoe",
            "password": "q8*]pRvv",
        }
        
+ Response 201

+ Request (application/json)
        
        {
            "username": "OrUsernameMoreThank20Symbols",
            "password": "OrPasswordIsMoreThan72Symbols",
            "password": "Ornot_confirmed"
        }
        
+ Response 422



## /users/login

### Вход в аккаунт [POST]

Лимит запросов: не более 10 в течение 20 секунд

+ Request (application/json)
        
        {
            "username": "JonhDoe",
            "password": "q8*]pRvv",
        }
        
+ Response 200 (application/json)
        
        {
            "token": "uaUeb8LqambbJYzbqvnwuiJw",
            "username": "JonhDoe",
        }

+ Request (application/json)
        
        {
            "username": "JonhDoe",
            "password": "InvalidPassword",
        }
        
+ Response 422

## /users/logout

### Выход из аккаунта [DELETE]

+ Request

    + Headers
    
            Authorization: uaUeb8LqambbJYzbqvnwuiJw
        
+ Response 204

+ Request

    + Headers
    
            Authorization: invalid_token
        
+ Response 401

# Group Временное

## /users

### Список ста последних пользователей [GET]

+ Response 200 (application/json)

        [
            {
                "id": "1",
                "username": "JohnDoe",
                "created_at": "2019-09-01T07:18:06.764Z",
            }, {
                "id": "2",
                "username": "JaneDoe",
                "created_at": "2019-09-01T07:19:12.045Z",
            },
        ]


## /users/drop

### Удаление всех пользователей [DELETE]

+ Response 204
    
## /protected/index

### Проверка авторизации [GET]

+ Request

    + Headers
    
            Authorization: uaUeb8LqambbJYzbqvnwuiJw
        
+ Response 200 (application/json)
        
        {
            "username": "JonhDoe",
        }

+ Request

    + Headers
    
            Authorization: invalid_token
        
+ Response 401